#include "myicon.hpp"
#include "ui_mainwindow.h"

MyIcon::MyIcon(QObject *parent)
    : QObject(parent)
    , ui(new Ui::MainWindow)
{
    
}

void MyIcon::setIcons(Ui::MainWindow *ui, bool isDark)
{
    QIcon icon;

    if (isDark) {
        icon.addFile(QString::fromUtf8(
                         ":/breeze-icons-master/icons-dark/actions/32/document-open.svg"),
                     QSize(),
                     QIcon::Normal,
                     QIcon::Off);
        ui->actionOpenImage->setIcon(icon);
        icon.addFile(QString::fromUtf8(
                         ":/breeze-icons-master/icons-dark/actions/32/trim-to-selection.svg"),
                     QSize(),
                     QIcon::Normal,
                     QIcon::Off);
        ui->actionPreprocess->setIcon(icon);
        icon.addFile(QString::fromUtf8(":/breeze-icons-master/icons-dark/actions/32/edit-undo.svg"),
                     QSize(),
                     QIcon::Normal,
                     QIcon::Off);
        ui->actionRotate_Left->setIcon(icon);
        icon.addFile(QString::fromUtf8(":/breeze-icons-master/icons-dark/actions/32/edit-redo.svg"),
                     QSize(),
                     QIcon::Normal,
                     QIcon::Off);
        ui->actionRotate_Right->setIcon(icon);
        icon.addFile(QString::fromUtf8(
                         ":/breeze-icons-master/icons-dark/actions/32/zoom-fit-best.svg"),
                     QSize(),
                     QIcon::Normal,
                     QIcon::Off);
        ui->actionBest_Fit->setIcon(icon);
        icon.addFile(QString::fromUtf8(":/breeze-icons-master/icons-dark/actions/32/zoom-in.svg"),
                     QSize(),
                     QIcon::Normal,
                     QIcon::Off);
        ui->actionZoom_In->setIcon(icon);
        icon.addFile(QString::fromUtf8(":/breeze-icons-master/icons-dark/actions/32/zoom-out.svg"),
                     QSize(),
                     QIcon::Normal,
                     QIcon::Off);
        ui->actionZoom_Out->setIcon(icon);
        icon.addFile(QString::fromUtf8(
                         ":/breeze-icons-master/icons-dark/actions/32/document-new.svg"),
                     QSize(),
                     QIcon::Normal,
                     QIcon::Off);
        ui->actionCopy_to_clipboard->setIcon(icon);
        icon.addFile(QString::fromUtf8(
                         ":/breeze-icons-master/icons-dark/actions/32/document-close.svg"),
                     QSize(),
                     QIcon::Normal,
                     QIcon::Off);
        ui->actionClear_text->setIcon(icon);
        icon.addFile(
            QString::fromUtf8(
                ":/breeze-icons-master/icons-dark/actions/32/document-edit-decrypt-verify.svg"),
            QSize(),
            QIcon::Normal,
            QIcon::Off);
        ui->actionRecognize_text->setIcon(icon);
        icon.addFile(QString::fromUtf8(
                         ":/breeze-icons-master/icons-dark/actions/32/view-refresh.svg"),
                     QSize(),
                     QIcon::Normal,
                     QIcon::Off);
        ui->actionRotate->setIcon(icon);
        icon.addFile(QString::fromUtf8(":/breeze-icons-master/icons-dark/actions/32/configure.svg"),
                     QSize(),
                     QIcon::Normal,
                     QIcon::Off);
        ui->actionSettings->setIcon(icon);
        icon.addFile(QString::fromUtf8(
                         ":/breeze-icons-master/icons-dark/actions/32/help-whatsthis.svg"),
                     QSize(),
                     QIcon::Normal,
                     QIcon::Off);
        ui->actionAbout->setIcon(icon);
        icon.addFile(QString::fromUtf8(
                         ":/breeze-icons-master/icons-dark/devices/22/drive-multipartition.svg"),
                     QSize(),
                     QIcon::Normal,
                     QIcon::Off);
        ui->actionAdjust_image->setIcon(icon);
        icon.addFile(QString::fromUtf8(
                         ":/breeze-icons-master/icons-dark/actions/32/document-save.svg"),
                     QSize(),
                     QIcon::Normal,
                     QIcon::Off);
        ui->actionSave->setIcon(icon);
    } else {
        icon.addFile(QString::fromUtf8(":/breeze-icons-master/icons/actions/32/document-open.svg"),
                     QSize(),
                     QIcon::Normal,
                     QIcon::Off);
        ui->actionOpenImage->setIcon(icon);
        icon.addFile(QString::fromUtf8(
                         ":/breeze-icons-master/icons/actions/32/trim-to-selection.svg"),
                     QSize(),
                     QIcon::Normal,
                     QIcon::Off);
        ui->actionPreprocess->setIcon(icon);
        icon.addFile(QString::fromUtf8(":/breeze-icons-master/icons/actions/32/edit-undo.svg"),
                     QSize(),
                     QIcon::Normal,
                     QIcon::Off);
        ui->actionRotate_Left->setIcon(icon);
        icon.addFile(QString::fromUtf8(":/breeze-icons-master/icons/actions/32/edit-redo.svg"),
                     QSize(),
                     QIcon::Normal,
                     QIcon::Off);
        ui->actionRotate_Right->setIcon(icon);
        icon.addFile(QString::fromUtf8(":/breeze-icons-master/icons/actions/32/zoom-fit-best.svg"),
                     QSize(),
                     QIcon::Normal,
                     QIcon::Off);
        ui->actionBest_Fit->setIcon(icon);
        icon.addFile(QString::fromUtf8(":/breeze-icons-master/icons/actions/32/zoom-in.svg"),
                     QSize(),
                     QIcon::Normal,
                     QIcon::Off);
        ui->actionZoom_In->setIcon(icon);
        icon.addFile(QString::fromUtf8(":/breeze-icons-master/icons/actions/32/zoom-out.svg"),
                     QSize(),
                     QIcon::Normal,
                     QIcon::Off);
        ui->actionZoom_Out->setIcon(icon);
        icon.addFile(QString::fromUtf8(":/breeze-icons-master/icons/actions/32/document-new.svg"),
                     QSize(),
                     QIcon::Normal,
                     QIcon::Off);
        ui->actionCopy_to_clipboard->setIcon(icon);
        icon.addFile(QString::fromUtf8(":/breeze-icons-master/icons/actions/32/document-close.svg"),
                     QSize(),
                     QIcon::Normal,
                     QIcon::Off);
        ui->actionClear_text->setIcon(icon);
        icon.addFile(QString::fromUtf8(
                         ":/breeze-icons-master/icons/actions/32/document-edit-decrypt-verify.svg"),
                     QSize(),
                     QIcon::Normal,
                     QIcon::Off);
        ui->actionRecognize_text->setIcon(icon);
        icon.addFile(QString::fromUtf8(":/breeze-icons-master/icons/actions/32/view-refresh.svg"),
                     QSize(),
                     QIcon::Normal,
                     QIcon::Off);
        ui->actionRotate->setIcon(icon);
        icon.addFile(QString::fromUtf8(":/breeze-icons-master/icons/actions/32/configure.svg"),
                     QSize(),
                     QIcon::Normal,
                     QIcon::Off);
        ui->actionSettings->setIcon(icon);
        icon.addFile(QString::fromUtf8(":/breeze-icons-master/icons/actions/32/help-whatsthis.svg"),
                     QSize(),
                     QIcon::Normal,
                     QIcon::Off);
        ui->actionAbout->setIcon(icon);
        icon.addFile(QString::fromUtf8(
                         ":/breeze-icons-master/icons/devices/22/drive-multipartition.svg"),
                     QSize(),
                     QIcon::Normal,
                     QIcon::Off);
        ui->actionAdjust_image->setIcon(icon);
        icon.addFile(QString::fromUtf8(":/breeze-icons-master/icons/actions/32/document-save.svg"),
                     QSize(),
                     QIcon::Normal,
                     QIcon::Off);
        ui->actionSave->setIcon(icon);
    }
}
